### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [lmaw/Threedim#1]
In the files "quadcopter_calibration_esc_motor_vibration.ino" and "quadcopter_core1_v12.ino", there is waiting with timeout after the `Wire.requestFrom()`. That is not needed.

The code could be like this:
```
  Wire.requestFrom(IMUAddress, nbytes, (uint8_t)true); // Send a repeated start and then release the bus after reading

  if (Wire.available() != nbytes) {
    Serial.println(F("i2cRead request fail"));
    return 5; // This error value is not already taken by endTransmission
  }

  for (uint8_t _i = 0; _i < nbytes; _i++) {
    data[_i] = Wire.read();
  }
```
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)
Background story: http://arduinoforum.nl/viewtopic.php?f=12&t=2929

**Comment by lmaw** [comment]
Thank you!!! :)
